<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$this->headScript()->appendFile($this->assetUrl('js/browse.js'));
$layoutSetting = $this->themeSetting('browse_layout', 'grid');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$isGrid = (strpos($layoutSetting, 'grid') !== false) ? true : false;
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$bodyTruncate = $this->themeSetting('truncate_body_property');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;


$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse');
?>

<?php echo $this->pageTitle($translate('Item sets'), 2); ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-control-mobile">
<button type="button" class="browse-toggle closed"><?php echo $translate('Options'); ?></button>
</div>
<div class="browse-controls closed">
    <?php echo $this->pagination(); ?>
    <?php if (strpos($layoutSetting, 'toggle') !== false): ?>
    <div class="layout-toggle">
        <button type="button" aria-label="<?php echo $translate('Grid'); ?>" class="grid o-icon-grid" <?php echo $gridState; ?>></button>
        <button type="button" aria-label="<?php echo $translate('List'); ?>" class="list o-icon-list" <?php echo $listState; ?>></button>
    </div>
    <?php endif; ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resources <?php echo ($isGrid) ? 'resource-grid' : 'resource-list'; ?>">
<?php
foreach ($itemSets as $itemSet):

//** BEGIN MODM MODIFICATION **/
$heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]')]) : $itemSet->displayTitle(null, ($filterLocale ? [$lang, ''] : null));
$body = null;
if ($bodyTerm) {
    $bodyTermValue = $itemSet->value($bodyTerm);
    $bodyResource = $bodyTermValue ? $bodyTermValue->valueResource() : null;
    $body = ($bodyTermValue && $bodyResource) ? $bodyResource->displayTitle(null, ($filterLocale ? [$lang, ''] : null)) : $bodyTermValue;
} else {
    // Based on resource template
    $template = $itemSet->resourceTemplate();
    if ($template && $template->descriptionProperty()) {
        if (($filterLocale == 0) || !($bodyTermValue = $itemSet->value($template->descriptionProperty()->term(), ['lang' => $lang]))) {
            $bodyTermValue = $itemSet->value($template->descriptionProperty()->term());
        }
        if (null !== $bodyTermValue) {
            $bodyResource = $bodyTermValue ? $bodyTermValue->valueResource() : null;
            if ($bodyTermValue && $bodyResource) {
                if ($headingTerm) {
                    if (! ($body = $bodyResource->value($headingTerm, ['lang' => $lang]))) {
                        $body = $bodyResource->value($headingTerm, ['default' => $translate('[Untitled]')]);
                    }
                } else {
                    $template = $bodyResource->resourceTemplate();
                    if ($template && $template->titleProperty()) {
                        if (($filterLocale == 0)
                            || ! ($body = $bodyResource->value($template->titleProperty()->term(), ['lang' => $lang]))) {
                                $body = $bodyResource->value($template->titleProperty()->term());
                            }
                    }
                }
                if (!$body) {
                    $body = $bodyResource->displayTitle(null, ($filterLocale ? [$lang, ''] : null));
                }
            } else {
                $body = $bodyTermValue;
            }
        }
    }
}
if (!$body) {
    $body = $itemSet->displayDescription(null, ($filterLocale ? [$lang, ''] : null));
}
?>
    <li class="item-set resource <?php echo ($isGrid) ? '' : 'media-object'; ?>">
        <div class="resource-meta <?php echo ($isGrid) ? '' : 'media-object-section'; ?>">
            <?php

                // MODM
            echo $itemSet->linkRaw($this->thumbnail($itemSet, 'medium'), null, ['class' => 'thumbnail']);
                // \MODM
            ?>
            <h4><?php echo $itemSet->link($heading); ?></h4>
            <?php if ($body): ?>
            <div class="description"><?php echo $escape($body); ?></div>
            <?php endif; ?>
        </div>
    </li>
<?php //** END MODM MODIFICATION **/ ?>
<?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
