<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
$mediaDisplay = $this->themeSetting('media_display');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));

// MODM
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
// \MODM

$fullWidthMainBlockContent = $this->resourcePageBlocks($item, 'full_width_main');
$fullWidthMainHasBlocks = $fullWidthMainBlockContent->hasBlocks();
$mainWithSidebarBlockContent = $this->resourcePageBlocks($item);
$mainWithSidebarHasBlocks= $mainWithSidebarBlockContent->hasBlocks();
$leftSidebarBlockContent = $this->resourcePageBlocks($item, 'left');
$leftSidebarHasBlocks = $leftSidebarBlockContent->hasBlocks();
$rightSidebarBlockContent = $this->resourcePageBlocks($item, 'right');
$rightSidebarHasBlocks = $rightSidebarBlockContent->hasBlocks();

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$valueLang = $filterLocale ? [$lang, ''] : null;
?>

<div class="resource-title">
<?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>

// BEGIN MODM MODIFICATION
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$body = null;
if ($bodyTerm) {
    $bodyTermValue = $item->value($bodyTerm);
    $bodyResource = $bodyTermValue ? $bodyTermValue->valueResource() : null;
    $body = ($bodyTermValue && $bodyResource) ? $bodyResource->displayTitle(null, ($filterLocale ? [$lang, ''] : null)) : $bodyTermValue;
} else {
    // Based on resource template
    $template = $item->resourceTemplate();
    if ($template && $template->descriptionProperty()) {
        if (($filterLocale == 0) || !($bodyTermValue = $item->value($template->descriptionProperty()->term(), ['lang' => $lang]))) {
            $bodyTermValue = $item->value($template->descriptionProperty()->term());
        }
        if (null !== $bodyTermValue) {
            $bodyResource = $bodyTermValue ? $bodyTermValue->valueResource() : null;
            if ($bodyTermValue && $bodyResource) {
                if ($headingTerm) {
                    if (! ($body = $bodyResource->value($headingTerm, ['lang' => $lang]))) {
                        $body = $bodyResource->value($headingTerm, ['default' => $translate('[Untitled]')]);
                    }
                } else {
                    $template = $bodyResource->resourceTemplate();
                    if ($template && $template->titleProperty()) {
                        if (($filterLocale == 0)
                            || ! ($body = $bodyResource->value($template->titleProperty()->term(), ['lang' => $lang]))) {
                                $body = $bodyResource->value($template->titleProperty()->term());
                            }
                    }
                }
                if (!$body) {
                    $body = $bodyResource->displayTitle(null, ($filterLocale ? [$lang, ''] : null));
                }
            } else {
                $body = $bodyTermValue;
            }
        }
    }
}
// END MODM MODIFICATION
?>

<div class="resource-title">
<!--  MODM - Ajout description dans le titre -->
<?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2, ($body ? $escape($body) : '')); ?>
<!--  /MODM -->
<h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>

<div class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>
    <?php if ($fullWidthMainHasBlocks): ?>
    <div class="full-width-main">
        <?php echo $fullWidthMainBlockContent->getBlocks(); ?>
        <!--  MODM -->   
        <!-- TODO: Déplacer dans une sidebar? --> 	
    	<div id="resource-controls">
        	<?php if ($item->userIsAllowed('update')): ?>
            <a target="_blank" href="<?php echo $item->adminUrl('edit'); ?>" class="button"><?php echo $translate('Edit item'); ?></a>
            <?php endif; ?>
        </div>
    	<!-- \MODM -->
    </div>
    <?php endif; ?>

    <?php if ($mainWithSidebarHasBlocks || $leftSidebarHasBlocks || $rightSidebarHasBlocks): ?>
    
    <?php 
    if ($leftSidebarHasBlocks && $rightSidebarHasBlocks) {
        $sidebarWidth = '3';
        $mainWidth = '6';
    } else {
        $sidebarWidth = '4';
        $mainWidth = '8';
    }
    ?>
    
    <div class="grid-x grid-margin-x">
        <?php if ($leftSidebarHasBlocks): ?>
        <div class="left-sidebar cell medium-<?php echo $sidebarWidth; ?>">
            <?php echo $leftSidebarBlockContent->getBlocks(); ?>
        </div>
        <?php endif; ?>

        <?php if ($mainWithSidebarHasBlocks): ?>
        <div class="main-with-sidebar cell medium-<?php echo $mainWidth; ?>">
            <?php echo $mainWithSidebarBlockContent->getBlocks(); ?>
        </div>
        <?php endif; ?>

        <?php if ($rightSidebarHasBlocks): ?>
        <div class="right-sidebar cell medium-<?php echo $sidebarWidth; ?>">
            <?php echo $rightSidebarBlockContent->getBlocks(); ?>
        </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>

    <?php $this->trigger('view.show.after'); ?>
</div>
