<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');


$this->headScript()->appendFile($this->assetUrl('js/swiper-bundle.min.js'));


?>

<div class="resource-title">
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>

<div class="grid-x">

    <?php if ($itemMedia): ?>
    <div id="swiper">
        <!-- Main Slider main container -->
        <div class="swiper-container media-slider">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">

            <?php foreach ($itemMedia as $media): ?>

                <!-- Slides -->
                <div class="swiper-slide">
                	<div class="swiper-zoom-container">
              			<img class="swiper-lazy" data-src="<?php echo $media->originalUrl();?>" alt=""/>
              		</div>
              		<div class="swiper-lazy-preloader"></div>
    			</div>

            <?php endforeach; ?>
            </div>
            <!-- If we need pagination -->
            <div class="swiper-pagination"></div>

            <!-- If we need navigation buttons -->
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    </div>

    <div id="thumbnail-swiper">
        <!-- Main Slider main container -->
        <div class="swiper-container thumbs-slider">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">

            <?php foreach ($itemMedia as $media): ?>

                <!-- Slides -->
                <div class="swiper-slide">
          			<img src="<?php echo $escape($media->thumbnailUrl('square')); ?>" alt=""/>
    			</div>

            <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php endif; ?>

<div id="resource-values" class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $item->displayValues(); ?>
    <?php $itemSets = $item->itemSets(); ?>
    <dl>
    <?php if (count($itemSets) > 0): ?>
    <div class="property">
        <dt><?php echo $translate('Item sets'); ?></dt>
        <div class="values">
            <?php foreach ($itemSets as $itemSet): ?>
            <dd class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></dd>
            <?php endforeach; ?>
        </div>
    </div>
    <?php endif; ?>
    </dl>

    <?php
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $item->displaySubjectValues($page, 25, $property);
    ?>
    <?php if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?php echo $translate('Linked resources'); ?></h3>
        <?php echo $subjectValues; ?>
    </div>
    <?php endif; ?>

    <?php $this->trigger('view.show.after'); ?>
</div>

</div>

<script>
    var thumbnailSwiper = new Swiper('.thumbs-slider', {
        slidesPerView: 5,
        spaceBetween: 30,
        centerSlides: true,
        pagination: false,
    });

    var swiper = new Swiper('.media-slider', {
        zoom: true,
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        navigation: {
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev',
        },
     // Disable preloading of all images
        preloadImages: false,
        // Enable lazy loading
        lazy: true,
        thumbs: {
            swiper: thumbnailSwiper
          }
    });
  </script>
