<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
$headingTerm = $this->siteSetting('browse_heading_property_term');

$filterLocale = $this->themeSetting('filter_locale_values');
$lang = $this->lang();

$this->headScript()->appendFile($this->assetUrl('js/lightslider.js'));
$this->headLink()->prependStylesheet($this->assetUrl('css/lightslider.css'));
$this->headScript()->appendFile($this->assetUrl('js/lightgallery.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-zoom.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-fullscreen.js'));
$this->headLink()->prependStylesheet($this->assetUrl('css/lightgallery.css'));
?>

<div class="resource-title">
<?php
	if ($headingTerm) {
	    if (!($itemTitle = $item->value($headingTerm, ['lang' => $lang]))) {
	        $itemTitle = $item->value($headingTerm, ['default' => $translate('[Untitled]')]);
	    }
	} else {
	    $template = $item->resourceTemplate();
	    if ($template && $template->titleProperty()) {
	        if (($filterLocale == 0) || !($itemTitle = $item->value($template->titleProperty()->term(), ['lang' => $lang]))) {
	            $itemTitle = $item->value($template->titleProperty()->term());
	        }
	    }
	}
	if (!$itemTitle) {
	    $itemTitle = $item->displayTitle();
	}
    echo $this->pageTitle($itemTitle, 2);
?>
<h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>

<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-slider">
    	<ul id="imageGallery">
    	<?php foreach ($itemMedia as $media): ?>
  			<li data-thumb="<?php echo $escape($media->thumbnailUrl('square')); ?>" data-src="<?php echo $media->originalUrl(); ?>">
    			<img src="<?php echo $escape($media->thumbnailUrl('large')); ?>" />
  			</li>
  		<?php endforeach; ?>
		</ul>
	</div>
<?php endif; ?>

<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<div class="grid-x">

<div id="resource-controls">
	<?php if ($item->userIsAllowed('update')): ?>
    <a target="_blank" href="<?php echo $item->adminUrl('edit'); ?>" class="button"><?php echo $translate('Edit item'); ?></a>
    <?php endif; ?>
</div>

<div id="resource-values" class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $item->displayValues(); ?>
    <?php $itemSets = $item->itemSets(); ?>
    <dl>
    <?php if (count($itemSets) > 0): ?>
    <div class="property">
        <dt><?php echo $translate('Item sets'); ?></dt>
        <div class="values">
            <?php foreach ($itemSets as $itemSet): ?>
            <?php
            $itemSetTitle = null;
            if ($headingTerm) {
                if (!($itemSetTitle = $itemSet->value($headingTerm, ['lang' => $lang]))) {
                    $itemSetTitle = $itemSet->value($headingTerm, ['default' => $translate('[Untitled]')]);
                }
            } else {
                $template = $itemSet->resourceTemplate();
                if ($template && $template->titleProperty()) {
                    if (($filterLocale == 0) || !($itemSetTitle = $itemSet->value($template->titleProperty()->term(), ['lang' => $lang]))) {
                        $itemSetTitle = $itemSet->value($template->titleProperty()->term());
                    }
                }
            }
            if (!$itemSetTitle) {
                $itemSetTitle = $itemSet->displayTitle();
            }
            ?>
            <dd class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSetTitle; ?></a></dd>
            <?php endforeach; ?>
        </div>
    </div>
    <?php endif; ?>
    </dl>

	<dl>
 	<?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>
 		<div class="property">
     		<dt><?php echo $translate('Site pages'); ?></dt>
     		<div class="values">
         		<?php foreach ($sitePages as $sitePage): ?>
         		<dd class="value"><?php echo $sitePage->link($sitePage->title()); ?></dd>
         		<?php endforeach; ?>
     		</div>
 		</div>
 	<?php endif; ?>
 	</dl>

    <?php
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $item->displaySubjectValues($page, 25, $property);
    ?>
    <?php if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?php echo $translate('Linked resources'); ?></h3>
        <?php echo $subjectValues; ?>
    </div>
    <?php endif; ?>

    <?php $this->trigger('view.show.after'); ?>
</div>

</div>

<script>
	$(document).ready(function() {
    var slider = $('#imageGallery').lightSlider({
		prevHtml: '<span class="custom-prev-html" style="color: black"><i class="fas fa-chevron-left"></i></span>',
		nextHtml: '<span class="custom-next-html" style="color: black"><i class="fas fa-chevron-right"></i></span',
        gallery:true,
        item:1,
        adaptiveHeight: true,
        thumbItem: 8,
        thumbMargin: 30,

        responsive : [
            {
                breakpoint:800,
                settings: {
                    thumbItem:5,
                    slideMargin:10,
                  }
            },
            {
                breakpoint: 520,
                settings: {
                    thumbItem:4,
                    slideMargin: 5,
                  }
            }
        ],

        onSliderLoad: function(el) {
            el.lightGallery({
                selector: '#imageGallery .lslide',
                download: false,
        		fullScreen: true,
        		zoom: true,
        		actualSize: true,
            });
        }
    });
  });
  </script>
